import type { Metadata } from "next";
import { oxygenFont } from "@/app/fonts";
import "./globals.css";
import DashboardLayout from "./ui/dashboard-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oxygenFont.className} antialiased`}>
        <main>
          <DashboardLayout>{children}</DashboardLayout>
        </main>
      </body>
    </html>
  );
}
